// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClg2vFBwHZ7ulerlv7Y8-rXtzMy1jj6yw',
    appId: '1:784401057035:web:7ba1538c4a247ab1aece0e',
    messagingSenderId: '784401057035',
    projectId: 'marjeno-b3b0f',
    authDomain: 'marjeno-b3b0f.firebaseapp.com',
    storageBucket: 'marjeno-b3b0f.firebasestorage.app',
    measurementId: 'G-GRJ4VY6RLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcTGjuLrwW-G5Q-wtjhn2igDNP9tfUSG0',
    appId: '1:784401057035:android:a1ecb2adea9ef0d2aece0e',
    messagingSenderId: '784401057035',
    projectId: 'marjeno-b3b0f',
    storageBucket: 'marjeno-b3b0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNY3VlvLOKm19LSbJTv-BlNoDdz0LxbMU',
    appId: '1:784401057035:ios:2fe683c840cfe187aece0e',
    messagingSenderId: '784401057035',
    projectId: 'marjeno-b3b0f',
    storageBucket: 'marjeno-b3b0f.firebasestorage.app',
    iosBundleId: 'com.example.marjeno',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNY3VlvLOKm19LSbJTv-BlNoDdz0LxbMU',
    appId: '1:784401057035:ios:2fe683c840cfe187aece0e',
    messagingSenderId: '784401057035',
    projectId: 'marjeno-b3b0f',
    storageBucket: 'marjeno-b3b0f.firebasestorage.app',
    iosBundleId: 'com.example.marjeno',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClg2vFBwHZ7ulerlv7Y8-rXtzMy1jj6yw',
    appId: '1:784401057035:web:95133dc31b15ca5faece0e',
    messagingSenderId: '784401057035',
    projectId: 'marjeno-b3b0f',
    authDomain: 'marjeno-b3b0f.firebaseapp.com',
    storageBucket: 'marjeno-b3b0f.firebasestorage.app',
    measurementId: 'G-6HGKCQ742Q',
  );
}
